### ISSUE TITLE
Fedora 25

### ISSUE THREAD

**Issue by kornrunner** [kyl191/nginx-mainline#2]
Have you planned to support Fedora 25 as well? Any chance of refreshing this package?

Thanks!

**Comment by kyl191** [comment]
Yep - I'm on a break right now after finishing an internship. I'll bump the spec file and push out the latest nginx version tonight.

**Comment by kornrunner** [comment]
Thank you very much!

**Comment by kyl191** [comment]
https://github.com/kyl191/nginx-mainline/commit/7de305fb591fe27d74b0a3101e1abb5be1915770 fixes it, packages have been built in the copr repo.

**Comment by kornrunner** [comment]
Pretty much the same question, but now it's about Fedora 27. Any chance of supporting it? Thank you!
